### ISSUE TITLE
Two Claims added with same type, but different value

### ISSUE THREAD

**Issue by kevfromireland** [TerribleDev/OwinOAuthProviders#100]
I'm not sure if this is a bug as I don't know the OAuth spec, but it seems weird...

In `SalesforceAuthenticationHandler`, at Line [111](https://github.com/RockstarLabs/OwinOAuthProviders/blob/master/Owin.Security.Providers/Salesforce/SalesforceAuthenticationHandler.cs#L11) the Salesforce username is stashed away against a claim type of `http://schemas.xmlsoap.org/ws/2005/05/identity/claims/name` .

Then, at Line [131](github.com/RockstarLabs/OwinOAuthProviders/blob/master/Owin.Security.Providers/Salesforce/SalesforceAuthenticationHandler.cs#L131) of the same file, the `DisplayName` is stashed away against the same claim type of `http://schemas.xmlsoap.org/ws/2005/05/identity/claims/name` .

I _think_ this means you can't disambiguate between those two values, or is that expected behaviour?

**Comment by jerriep** [comment]
Thanks for pointing out the discrepancy. The correct value for that claim is the username. I made the change.

**Comment by jerriep** [comment]
Fixed in 4944f396c75179d462ebb75a3a74a216ae1c599b

**Comment by kevfromireland** [comment]
you sir, are awesome. Thanks for the quick turnaround @jerriep !
