### ISSUE TITLE
Yahoo provider does not get email

### ISSUE THREAD

**Issue by mitja-p** [TerribleDev/OwinOAuthProviders#101]
There is a bug in Yahoo provider and due to exception you cannot get the email.

This code in YahooAuthenticatedContext.cs raises exception:
                            // Try and get the primary email address
                            email = emails.FirstOrDefault(e => e["primary"].ToString() == "true");

Correct would be:
e => e["primary"]!=null && e["primary"].ToString() == "true"

**Comment by jerriep** [comment]
A fix and a pull request will be appreciated, thanks :)

**Comment by mitja-p** [comment]
I am new to contributing directly to Github. But I think I have managed to create a pull request. If anything is wrong, tips are appreciated.

**Comment by jerriep** [comment]
It's perfect. Thanks for fix :)
