### ISSUE TITLE
LinkedIn AuthenticationProperties RedirectUri not being used

### ISSUE THREAD

**Issue by agrigg** [TerribleDev/OwinOAuthProviders#107]
I've got an MVC 5 application and I'm using the LinkedIn OAUTH provider. I noticed that when I pass a RedirectUri to the Challenge method in the AuthenticationProperties, it does not use it. Looking at the source code in the [LinkedInAuthenticationHandler.cs](https://github.com/RockstarLabs/OwinOAuthProviders/blob/master/Owin.Security.Providers/LinkedIn/LinkedInAuthenticationHandler.cs), instead of setting the redirectUri from the challenge.Properties, it overrides it:

```
string redirectUri =
    baseUri +
    Options.CallbackPath;

AuthenticationProperties properties = challenge.Properties;
if (string.IsNullOrEmpty(properties.RedirectUri))
{
    properties.RedirectUri = currentUri;
}
```

I believe this should be:

```
string redirectUri =
    baseUri +
    Options.CallbackPath;

AuthenticationProperties properties = challenge.Properties;
if (string.IsNullOrEmpty(properties.RedirectUri))
{
    redirectUri = properties.RedirectUri; // <- CHANGE HERE
}
```

Is there a reason it doesn't honor the redirectUri sent in and always uses the existing url?

**Comment by agrigg** [comment]
BTW, if this change is appropriate, I would be happy to submit a pull request.

**Comment by jerriep** [comment]
Can you please explain what Challenge method it is that you are referring to? Can you perhaps give a small demo project demonstrating the behaviour which is not working?

**Comment by agrigg** [comment]
Let me explain at a high level what I'm trying to accomplish, then I can answer you specific question.

LinkedIn requires that you register the callback url that you will be using with them as part of the API setup. They also don't support wildcard domains. I have a site where there are different communities, each with their own subdomain. Since it isn't practical to add a record in LinkedIn for each subdomain (plus there is a limit of 50) my solution was to always give the same subdomain for the callback url and register that with LinkedIn. So, for example:

If the user is on community.mysite.com (or community2.mysite.com, etc) I always want to send LinkedIn a redirectURL of app.mysite.com/signin-linkedin which I have registered with LinkedIn. When I use the LinkedIn provider in this library even if I pass a custom RedirectUri through the AuthenticationProperties it isn't used and the current url is used instead. So, in this case it uses community.mysite.com/signin-linkedin which is not registered with LinkedIn and so throws an error from LinkedIn saying it is not an authorized URL.

To answer your question about the Challenge method, I'm using the boilerplate from a new MVC project with ASP.NET Identity enabled:

```
[HttpPost]
[AllowAnonymous]
public ActionResult ExternalLogin(string provider, string returnUrl)
{
    // Generate callback url always using app.mysite.com as the host
    var url = Url.Action("ExternalLoginCallback", "home", new RouteValueDictionary(new { area = "account", ReturnUrl = returnUrl}), Request.Url.Scheme, "app.mysite.com");

    return new ChallengeResult(provider, url);
}

private class ChallengeResult : HttpUnauthorizedResult
{
    public ChallengeResult(string provider, string redirectUri) : this(provider, redirectUri, null)
    {
    }

    public ChallengeResult(string provider, string redirectUri, string userId)
    {
        LoginProvider = provider;
        RedirectUri = redirectUri;
        UserId = userId;
    }

    public string LoginProvider { get; set; }
    public string RedirectUri { get; set; }
    public string UserId { get; set; }

    public override void ExecuteResult(ControllerContext context)
    {
        var properties = new AuthenticationProperties() { RedirectUri = RedirectUri };
        if (UserId != null)
        {
            properties.Dictionary[XsrfKey] = UserId;
        }
        // Pass RedirectUri to Challenge method, but never gets used
        context.HttpContext.GetOwinContext().Authentication.Challenge(properties, LoginProvider);
    }
}
```

Does that give you enough info?

**Comment by jerriep** [comment]
Yeah, I think I understand your issue.

The redirect URI you specify in the ChallengeResult, is the URI where the user should be redirected to after they signed in successfully.

The redirect URI which is used inside the OAuth provider is a completely different thing. This is where LinkedIn will redirect back to your application and the OWIN middleware will intercept that callback and pass it on the the correct OAuth provider (the LinkedIn provider in this case) to complete the rest of the authentication process (i.e. extracting the user information from LinkedIn).

This OAuth redirect URI will **always** be calculated based on the application's base URL with `CallbackPath` appended to that. This behaviour is consistent across all the OAuth providers - even the ones created by Microsoft.

My suggestion would be to create an "authentication subdomain" for your app. So let all authentication happen on http://account.mysite.com and then redirect the user to the specific tenant subdomain after that.

**Comment by agrigg** [comment]
Got it, makes sense. I had just thought about that as I was writing up my last comment. Thanks for your help.

**Comment by jerriep** [comment]
Pleasure :) Hope you manage to sort it out.
