### ISSUE TITLE
GetExternalLoginInfoAsync always return null or did I miss something?

### ISSUE THREAD

**Issue by warheat1990** [TerribleDev/OwinOAuthProviders#108]
So I'm using using `Owin.Security.Providers.Steam`, basically I just register it in `Startup.Auth.cs` like this `app.UseSteamAuthentication("mysecretid");`. But after I login, `GetExternalLoginInfoAsync` always return `null`. I checked the response with fiddler and it seems Steam is returning the correct data.

```
"response": {
        "players": [
            {
                "steamid": "76561198057961078",
                "communityvisibilitystate": 3,
                "profilestate": 1,
                "personaname": "Press \"R\" to restart™",
                "lastlogoff": 1435947642,
                "commentpermission": 2,
                "profileurl": "http://steamcommunity.com/id/warheat1990/",
                "avatar": "https://steamcdn-a.akamaihd.net/steamcommunity/public/images/avatars/59/598fa035b19342a9e0b26a8115e8ddc5da0cc900.jpg",
                "avatarmedium": "https://steamcdn-a.akamaihd.net/steamcommunity/public/images/avatars/59/598fa035b19342a9e0b26a8115e8ddc5da0cc900_medium.jpg",
                "avatarfull": "https://steamcdn-a.akamaihd.net/steamcommunity/public/images/avatars/59/598fa035b19342a9e0b26a8115e8ddc5da0cc900_full.jpg",
                "personastate": 1,
                "primaryclanid": "103582791434936111",
                "timecreated": 1327988764,
                "personastateflags": 0
            }
        ]

    }
```

I tried Reddit oAuth and `GetExternalLoginInfoAsync` also return `null`. Am I missing something?

**Comment by jerriep** [comment]
Sorry, I do not have much capacity right now to debug this.

If you don't mind, could you please create a fork of the repo, debug it locally and create a pull request?

**Comment by warheat1990** [comment]
Turned out I'm an idiot. I put the `app.UseSteamAuthentication("mysecretid");` at the bottom of the method and it worked. Cheers.

Closed
