### ISSUE TITLE
Change Reddit Scope default value

### ISSUE THREAD

**Issue by warheat1990** [TerribleDev/OwinOAuthProviders#109]
Is it possible to change reddit scope property value? Because it is readonly and I don't see any overload in the constructor.

Basically the default value 

```
 Scope = new List<string>
        {
            "identity",
            "mysubreddits",
            "privatemessages"
        };
```

is overkill because I only need `identity` and my user won't allow my application to access their private message. Is there any reason why is it set to readonly?

**Comment by jerriep** [comment]
It is a list, so you can call `Clear()` to clear all the values.

See http://www.oauthforaspnet.com/providers/reddit/ under "Request extra (or less) permissions"
