### ISSUE TITLE
EveOnline Different Scopes

### ISSUE THREAD

**Issue by RemotecUK** [TerribleDev/OwinOAuthProviders#126]
Hi, is there a way to request different scopes using the EveOnline provider?

I _think_ that these are needed for example to get a refresh token and also to be able to get different data from the CREST API. 

I can see that the Scopes object in the `EveOnlineAuthenticationOptions` class has a private setter and the member variable is set to an empty list. This means at present it is not possible to add additional scopes (which may be by design).

In the future I understand that additional scopes will be used to get different data from the CREST API. One example of this is the "publicData" scope.

Please let me know if there is a way at present to do this.

Thanks.

References
http://eveonline-third-party-documentation.readthedocs.org/en/latest/sso/refreshtokens/
http://eveonline-third-party-documentation.readthedocs.org/en/latest/crest/authentication/

**Comment by RemotecUK** [comment]
Update: I can see that code exists in `EveOnlineAuthenticationHandler`to look for a refresh token and add it to the claims but I cannot see a way to request the token at this time. Thanks.

**Comment by jerriep** [comment]
The `Scopes` property is readonly, but it is a List so you can add items, remove items etc.

Here is an example of how to do it for Facebook:
http://www.oauthforaspnet.com/providers/facebook/

Have a look under the section "Request extra permissions". Like I said, this particular example is for Facebook, but the same principle applies.

**Comment by RemotecUK** [comment]
Thanks. I had structured my code incorrectly. Following the FB example worked perfectly.

**Comment by jerriep** [comment]
:+1:
