### ISSUE TITLE
Reason for Fitbit Scope to be private set?

### ISSUE THREAD

**Issue by mattferderer** [TerribleDev/OwinOAuthProviders#139]
In the OwinOAuthProviders/Owin.Security.Providers/Fitbit/FitbitAuthenticationOptions.cs file the scope has a private set. 

``` C#
public IList<string> Scope { get; private set; }
```

As far as I can see, there is no way to modify the list from  "activity", "nutrition", "profile", "settings", "sleep", "social", "weight". Is there a reason it is set to private or is there a way that I'm unaware of to modify the scope? @jmloeffler

**Comment by jmloeffler** [comment]
I don't think there was any particular reason.  I just modeled the fitbit provider after the github provider which has it set private and I never noticed.  There were a few other things with the fitbit provider that were caught when I ported it to the aspnet-contib project that I've been meaning to backport.  One of them is being more conservative with the default scope.  So if that's the reason you need to modify the scope then I apologize.

**Comment by jerriep** [comment]
Please keep it private to keep it in line with all the other providers.

@mattferderer It is just a list, so if you want to change the scope, you can use the `Clear()` method to clear it, and then call `Add()` to add the scopes you want.

See the "Request extra permissions" section on this page for an example:
http://www.oauthforaspnet.com/providers/facebook/

**Comment by mattferderer** [comment]
Thank you @jerriep. That helped a lot.
