### ISSUE TITLE
IE / LinkedIn always takes user to LinkedIn Auth page

### ISSUE THREAD

**Issue by SpartanDigitalDotNet** [TerribleDev/OwinOAuthProviders#145]
For LinkedIn accounts, Chrome works fine, but IE always takes the user to LinkedIn's permission/auth page after the user logs out and tries to login.  If they log back in, why are they re-authenticated via LinkedIn?

Also, I noticed that IsPersisted is always set to false when SignIn is called-- just curious why and when would be set it to true? I know this is two questions, but I'm trying to test to see if IsPersisted is related to the IE issue.

Any help is greatly appreciated.

**Comment by jerriep** [comment]
Whether LinkedIn asked the user to give permission again or not is up to LinkedIn. We have no control over that. I think it best to ask them about that.

As for the `IsPersisted` defaulting to false, I assume your are refering to what happens inside the AccountController? If so, then that is they way MS generates the AccountController by default. If you do not like it like that, then simply try setting it to true.

**Comment by SpartanDigitalDotNet** [comment]
@jerriep -- thank you for the reply.  AccountController, yes, plus seems like there's no change if IsPersisted is true or false.  As far as "up to LinkedIn", I'm curious as to why it just recently started this behavior and only on IE and Edge and not Chrome.

I went into LinkedIn and removed the application from the list and that seemed to have fixed it for now.  This is very odd behavior.

Thanks for your help.

**Comment by jerriep** [comment]
Yeah, I am not sure why LinkedIn behaves this way. They do some strange things sometimes ;)
