### ISSUE TITLE
Problem with OpenID provider

### ISSUE THREAD

**Issue by RufusJWB** [TerribleDev/OwinOAuthProviders#148]
I have an OpenID provider that is based on [MITREid](https://github.com/mitreid-connect/). It is exposed under https://iam-playground.ct.siemens.com/iam-services/0.1/oidc/ (not reachable from the Internet) and has a .well-known/openid-configuration that looks the following.

`{"request_parameter_supported":true,"claims_parameter_supported":false,"introspection_endpoint":"https://iam-playground.ct.siemens.com/iam-services/0.1/oidc/introspect","scopes_supported":["openid","profile","email","address","phone","offline_access","roles"],"issuer":"https://iam-playground.ct.siemens.com/iam-services/0.1/oidc/","userinfo_encryption_enc_values_supported":["A256CBC+HS512","A256GCM","A192GCM","A128GCM","A128CBC-HS256","A192CBC-HS384","A256CBC-HS512","A128CBC+HS256"],"id_token_encryption_enc_values_supported":["A256CBC+HS512","A256GCM","A192GCM","A128GCM","A128CBC-HS256","A192CBC-HS384","A256CBC-HS512","A128CBC+HS256"],"authorization_endpoint":"https://iam-playground.ct.siemens.com/iam-services/0.1/oidc/authorize","service_documentation":"https://iam-playground.ct.siemens.com/iam-services/0.1/oidc/about","request_object_encryption_enc_values_supported":["A256CBC+HS512","A256GCM","A192GCM","A128GCM","A128CBC-HS256","A192CBC-HS384","A256CBC-HS512","A128CBC+HS256"],"userinfo_signing_alg_values_supported":["HS256","HS384","HS512","RS256","RS384","RS512"],"claims_supported":["sub","name","preferred_username","given_name","family_name","middle_name","nickname","profile","picture","website","gender","zone_info","locale","updated_time","birthdate","email","email_verified","phone_number","address"],"claim_types_supported":["normal"],"op_policy_uri":"https://iam-playground.ct.siemens.com/iam-services/0.1/oidc/about","token_endpoint_auth_methods_supported":["client_secret_post","client_secret_basic","client_secret_jwt","private_key_jwt","none"],"token_endpoint":"https://iam-playground.ct.siemens.com/iam-services/0.1/oidc/token","response_types_supported":["code","token"],"request_uri_parameter_supported":false,"userinfo_encryption_alg_values_supported":["RSA-OAEP","RSA-OAEP-256","RSA1_5"],"grant_types_supported":["authorization_code","implicit","urn:ietf:params:oauth:grant-type:jwt-bearer","client_credentials","urn:ietf:params:oauth:grant_type:redelegate"],"revocation_endpoint":"https://iam-playground.ct.siemens.com/iam-services/0.1/oidc/revoke","userinfo_endpoint":"https://iam-playground.ct.siemens.com/iam-services/0.1/oidc/userinfo","token_endpoint_auth_signing_alg_values_supported":["HS256","HS384","HS512","RS256","RS384","RS512"],"op_tos_uri":"https://iam-playground.ct.siemens.com/iam-services/0.1/oidc/about","require_request_uri_registration":false,"id_token_encryption_alg_values_supported":["RSA-OAEP","RSA-OAEP-256","RSA1_5"],"jwks_uri":"https://iam-playground.ct.siemens.com/iam-services/0.1/oidc/jwk","subject_types_supported":["public","pairwise"],"id_token_signing_alg_values_supported":["HS256","HS384","HS512","RS256","RS384","RS512","none"],"registration_endpoint":"https://iam-playground.ct.siemens.com/iam-services/0.1/oidc/register","request_object_signing_alg_values_supported":["HS256","HS384","HS512","RS256","RS384","RS512"],"request_object_encryption_alg_values_supported":["RSA-OAEP","RSA-OAEP-256","RSA1_5"]}`

Can you give me a hint, what URL I'm supposed to use as ProviderLoginUri if I'm using OpenIDAuthenticationExtensions?

**Comment by jerriep** [comment]
I have very little knowledge of the Open ID provider, so I cannot help

@laedit any chance you have an answer for this?

**Comment by laedit** [comment]
The url should be https://iam-playground.ct.siemens.com/iam-services/0.1/oidc/, but since it is OpenID Connect (from the MITREid link), it is not supported by the OpenIDAuthentication.
But if I remember well, I think that Microsoft have provided a middleware component which support it.

**Comment by RufusJWB** [comment]
Thank you very much!
