### ISSUE TITLE
Github Email is blank

### ISSUE THREAD

**Issue by Eonasdan** [TerribleDev/OwinOAuthProviders#149]
Thanks for providing all these providers.

I'm trying to setup my application to use GitHub logins, however the email field is null.

![image](https://cloud.githubusercontent.com/assets/1006516/14400828/e6b991f8-fdcc-11e5-8eb4-edc32bfdfd5a.png)

Quick Watch on `context.User`
![image](https://cloud.githubusercontent.com/assets/1006516/14400829/e978c7d8-fdcc-11e5-952c-6f2d06bedbb0.png)

Quick Watch on `var loginInfo = await AuthenticationManager.GetExternalLoginInfoAsync()`
![image](https://cloud.githubusercontent.com/assets/1006516/14400830/eba4a7de-fdcc-11e5-918b-cb0b43051594.png)

Am I missing something or is this a bug?

Perhaps this is related: https://github.com/thephpleague/oauth2-client/issues/9#issuecomment-20653139

**Comment by jerriep** [comment]
From this page:
https://developer.github.com/v3/users/

"Note: The returned email is the user's publicly visible email address (or null if the user has not specified a public email address in their profile)."

**Comment by Eonasdan** [comment]
My email address is public:

![image](https://cloud.githubusercontent.com/assets/1006516/14404135/79bb8b1c-fe3d-11e5-9073-5517f198a8a2.png)

If I use the http api my email address is there:

![image](https://cloud.githubusercontent.com/assets/1006516/14404145/90b164ea-fe3d-11e5-9394-d1cc26978112.png)

**Comment by jerriep** [comment]
The GH provider is not calling that endpoint. It is calling https://api.github.com/user

Docs here:
https://developer.github.com/v3/users/#get-the-authenticated-user

**Comment by Eonasdan** [comment]
Looks I was missing this on the profile screen (which I thought I checked)

![image](https://cloud.githubusercontent.com/assets/1006516/14404294/0bd65d2c-fe40-11e5-9278-8afa3550c5b6.png)

Thanks for the assistance.

**Comment by Eonasdan** [comment]
I just made a PR that will issue a second request to `user/emails` if `context.Email` is null. This should provide the users primary, verified email address if the scope authorizes that.
