### ISSUE TITLE
NETFramework,Version=v4.5 error on update to 2.0

### ISSUE THREAD

**Issue by totpero** [TerribleDev/OwinOAuthProviders#159]
Hi, 
I have the 1.27.0 nuget version and when i try to update to last version i get this error:

`Could not install package 'Owin.Security.Providers.ArcGISOnline 2.0.0'. You are trying to install this package into a project that targets '.NETFramework,Version=v4.5', but the package does not contain any assembly references or content files that are compatible with that framework. For more information, contact the package author.`

**Comment by TerribleDev** [comment]
I think the minimum version got accidentally bumped to 4.5.2 which is currently the lowest supported version from msft..that being said we should be able to target 4.5...I'll downgrade the packages

**Comment by TerribleDev** [comment]
@totpero  in the short term you can retarget your app to .net 4.5.2...or you can wait..later this week I'll plan on retargeting 4.5

**Comment by totpero** [comment]
@tparnell8 i will wait to downgrade.
Thanks. :+1:  you do grate job.

**Comment by TerribleDev** [comment]
retargeted in 2.3.0
