### ISSUE TITLE
Documentation Domain Exipred

### ISSUE THREAD

**Issue by patrickrobbins** [TerribleDev/OwinOAuthProviders#165]
The domain http://www.beabigrockstar.com/ has expired

**Comment by TerribleDev** [comment]
Thanks this was @jerriep's blog. @jerriep did you move the posts?

**Comment by jerriep** [comment]
My blog is now at http://www.jerriepelser.com

But I moved all the guides of my blog as well, and they are now at http://www.oauthforaspnet.com
