### ISSUE TITLE
Support for ASP.NET Core

### ISSUE THREAD

**Issue by SimonLuckenuik** [TerribleDev/OwinOAuthProviders#172]
ASP.NET Core 1.0 final (https://www.microsoft.com/net/core) was released earlier this week, it would be great to support it.
Thanks!

**Comment by TerribleDev** [comment]
That is what this project is for: https://github.com/aspnet-contrib/AspNet.Security.OAuth.Providers 

This repo targets Microsoft.Owin.Security which is part of the authorization strategy with apps platted ontop of OWIN.

In AspNet Core land the owin abstraction is a little higher, and the security packages work differently. I don't think this repo will ever be compatible with the new runtimes. 

That being said if Microsoft made Microsoft.Owin and Microsoft.Owin.Security run on core, then theoretically these packages could target std library 1.5
