### ISSUE TITLE
How can I get the AccessToken in TwitchAuthenticatedContext ?

### ISSUE THREAD

**Issue by embiem** [TerribleDev/OwinOAuthProviders#180]
Hey, I am rather new to ASP.NET and this plugin. I can't seem to find a way to access the oauth access token, that is stored in the TwitchAuthenticatedContext, after a user logged in using their Twitch account.

I need this token to make API requests on the TwitchAPI.

In Startup.Auth.cs I have added to ConfigureAuth():
`var opt = new TwitchAuthenticationOptions()
            {
                ClientId = "<myClientId>",
                ClientSecret = "<myClientSecret",
                Provider = new TwitchAuthenticationProvider()
                {
                    OnAuthenticated = async z =>
                    {
                        z.Identity.AddClaim(new Claim("Picture", z.User.GetValue("logo").ToString()));
                        System.Diagnostics.Debug.WriteLine(z.AccessToken);
                    }
                },
                Scope = { "user_read", "chat_login" }
            };
app.UseTwitchAuthentication(opt);`

this allows me to successfully log in using my twitch account and the Debug.WriteLine also gives me the correct AccessToken. But how do I access this token e.g. in my Controller to make a TwitchAPI-Call?

I have also described my problem on the ASP.NET Getting Started forums: https://forums.asp.net/t/2104702.aspx

Thank you for reading through my issue!

**Comment by TerribleDev** [comment]
Hey, if you read my response to this issue you can probably figure it out. https://github.com/TerribleDev/OwinOAuthProviders/issues/176 

The wordpress and twitch providers should be implemented in the same fashion.

**Comment by embiem** [comment]
Thanks! The [stackoverflow link](http://stackoverflow.com/questions/18942196/how-to-access-facebook-private-information-by-using-asp-net-identity-owin/19549581#19549581) in the other issue helped me out.

I ended up overriding the SignInAsync in my SignInManager and setting the external properties as claims on the new identity. Thanks!
