### ISSUE TITLE
loginInfo returns null when authenticate with salesforce

### ISSUE THREAD

**Issue by diwu86** [TerribleDev/OwinOAuthProviders#182]
Hi, I am currently running the demo app provided by OwinOAuthProviders. I uncomment here https://github.com/TerribleDev/OwinOAuthProviders/blob/master/OwinOAuthProvidersDemo/App_Start/Startup.Auth.cs#L127-L148 and add id and secret. When I click login, I can see the salesforce authentication page. After I click allow, it redirects me to the login page. The issue is here  https://github.com/TerribleDev/OwinOAuthProviders/blob/master/OwinOAuthProvidersDemo/Controllers/AccountController.cs#L208, loginInfo is null. But when I test with the googlePlus login, it's not null and redirects me to the register page. This is happening the same in my own app. Can someone help? Thanks

**Comment by diwu86** [comment]
Hi I find something interesting. Here https://github.com/TerribleDev/OwinOAuthProviders/blob/master/src/Owin.Security.Providers.Salesforce/SalesforceAuthenticationOptions.cs#L126, if I set scope as new List<string>{"email"}, it's working. Since the set for scope is private, I cannot override this in demo app. I am guessing something has been changed that salesforce is requiring "email" now?

**Comment by TerribleDev** [comment]
@diwu86 you could do Scope.Add("email") since private set does not protect against mutation. This was actually done on purpose so people could add to the scopes, but not replace the actual list object.

**Comment by diwu86** [comment]
thanks @TerribleDev  It's working now.
