### ISSUE TITLE
Please remove me as owner of the NuGet package

### ISSUE THREAD

**Issue by jerriep** [TerribleDev/OwinOAuthProviders#186]
Hi Tommy,

Contacted you through the contact form on NuGet a while ago to ask that you remove me as owner of the NuGet package (https://www.nuget.org/packages/Owin.Security.Providers/), but it seems you probably did not get that notification.

Can you please remove me as owner? 

I still get notifications when you publish new updates, and there is no way I can turn of notifications on a per-package basis. In any case since I have no involvement with the project anymore I should not be an owner of the NuGet package either.

Thanks!

**Comment by TerribleDev** [comment]
@jerriep, I'll do that, of course! it seems nuget sent me an email, but I must have missed it. Sorry 'bout that. I'll get on that before we publish any more updates.

**Comment by TerribleDev** [comment]
@jerriep you should now be off

**Comment by jerriep** [comment]
Thanks a lot Tommy :)

**Comment by jerriep** [comment]
Yep, thanks :)

**Comment by TerribleDev** [comment]
No problem!
