### ISSUE TITLE
Twitch - Redirect Mismatch

### ISSUE THREAD

**Issue by achrylex** [TerribleDev/OwinOAuthProviders#198]
Tried testing with a new MVC ASP.NET 4.5.2 project. 
Using default localhost and port settings in the application's Twitch Redirect URI settings "http://localhost:53408/".

Applied current sample code to Startup.Auth.cs
```
public void ConfigureAuth(IAppBuilder app)
{
            // Enable the application to use a cookie to store information for the signed in user
            app.UseCookieAuthentication(new CookieAuthenticationOptions
            {
                AuthenticationType = DefaultAuthenticationTypes.ApplicationCookie,
                LoginPath = new PathString("/Account/Login")
            });
            // Use a cookie to temporarily store information about a user logging in with a third party login provider
            app.UseExternalSignInCookie(DefaultAuthenticationTypes.ExternalCookie);

            //Simple Twitch Sign-in
            app.UseTwitchAuthentication("myclientid","myclientsecret");
}
```
Button is enabled on login, brings me to Twitch. Once I authorize my account, I am returned back to localhost with this:

http://localhost:53408/?error=redirect_mismatch&error_description=Parameter+redirect_uri+does+not+match+registered+URI...

Is there something that's missing?

**Comment by TerribleDev** [comment]
is twitch trying to redirect with https?

**Comment by TerribleDev** [comment]
what did you register as your redirect uri with twitch?

**Comment by achrylex** [comment]
I don't think it's trying to redirect with https. My project currently does
NOT have SSL enabled.

This is what I registered with twitch: http://localhost:53408/

This is identical to what's in my Project properties.

**Comment by TerribleDev** [comment]
@lexyoussef you need to register `http://localhost:53408/signin-Twitch` sorry if it was not obvious

**Comment by achrylex** [comment]
Ah, thank you! Yes that worked immediately. Apologies for reporting this as an issue, I'm fairly new to OAuth and I couldn't find a solution elsewhere.

Where would I have found documentation to register that URI?

**Comment by achrylex** [comment]
Nevermind, just noticed it in the comments. That's embarrassing. Well thank you again for your time and help!

**Comment by TerribleDev** [comment]
yeah sorry, we had a blog with a lot more info. At some point I plan on circling back and setting that up again.

**Comment by achrylex** [comment]
No problem! I'd certainly appreciate a blog, but I'm grateful for your help
as I can now get started with the rest of the features.

Thanks again!

**Comment by speed123400** [comment]
Do we need to create a signin-Twitch page to handle what Twitch sends back?
