### ISSUE TITLE
Request for new "WP OAuth" provider

### ISSUE THREAD

**Issue by ms000** [TerribleDev/OwinOAuthProviders#203]
I have been trying to implement a provider for WP OAuth, an OAuth server plugin for WordPress, so far without success.  I have an MVC 5 project and I am trying to setup a single sign-on solution.

[https://wp-oauth.com/](url)

I am not sure if this request is appropriate on GitHub, but I would like to see if anyone would like to help me with this on a paid basis.

Thanks,
Mark

**Comment by ms000** [comment]
Nevermind.  I finally got it working.

**Comment by TerribleDev** [comment]
👍 glad you got it working!
