### ISSUE TITLE
Is there a way to get a signed (strong named) version?

### ISSUE THREAD

**Issue by smailliwnosaj** [TerribleDev/OwinOAuthProviders#209]
I have a signed project.  I wish to include Owin.Security.Providers.OpenID from NuGet.  However, it is not a strong named dll.  Is there a way to get a strong named version?

**Comment by TerribleDev** [comment]
Not as of this moment, no. How useful would this be to you?

**Comment by smailliwnosaj** [comment]
For us, it is pretty much a go or no go for using it.  Is it possible to pull down the code, build, and sign it ourselves?

**Comment by TerribleDev** [comment]
You can do whatever the [license](https://github.com/TerribleDev/OwinOAuthProviders/blob/master/license.txt) lets you do, so long as you adhere to its terms, and restrictions. 

I can create a separate set of packages with a `-signed` suffix that will be strong named, however Saturday would probably be the **earliest** I can get to that.

**Comment by smailliwnosaj** [comment]
We would greatly appreciate that.  It would save us from having to replace our existing implementation with a different provider.  Would you be able to make it available through NuGet?  We have time.  So, no rush.  As long as we know it would be coming in the future, we can hold off any dev work.

**Comment by TerribleDev** [comment]
@smailliwnosaj I'll try to get a package pushed out within the next week. In the interim you can copy the source files into your own project.

**Comment by TerribleDev** [comment]
@smailliwnosaj in `2.15.1` all assemblies should now be strong named. Please let me know if you need anything else.

**Comment by smailliwnosaj** [comment]
Thanks, T;

I really appreciate your time on this.  When I am back in the office, Monday, I'll take a look.

**Comment by smailliwnosaj** [comment]
I am able to include OpenID and OpenIDBase in my project with signing turned on.  

Thanks again.   You're a lifesaver.

**Comment by TerribleDev** [comment]
np 👍
