### ISSUE TITLE
vb.net or c# sample for spotify

### ISSUE THREAD

**Issue by ghost** [TerribleDev/OwinOAuthProviders#212]
hello
please, can anyone give me a sample for spotify on vb.net or c#
thanks in advance

**Comment by TerribleDev** [comment]
This is already in the repo, is it not enough? 

 https://github.com/TerribleDev/OwinOAuthProviders/blob/master/OwinOAuthProvidersDemo/App_Start/Startup.Auth.cs#L219

**Comment by ghost** [comment]
thanks!
