### ISSUE TITLE
Pin all projects lang version to 6

### ISSUE THREAD

**Issue by TerribleDev** [TerribleDev/OwinOAuthProviders#217]
We should set the `<LangVersion>` to 6 in all csproj files. See this gist for details https://gist.github.com/TerribleDev/39fc4f17202ebe0f8dc6cdef4594a079

**Comment by AlastairBateman** [comment]
If the sole reason is to advance the version without any functional advantage it can probably be held off? One would assume people are using more reason versions but you wouldn't want to break anything.

**Comment by TerribleDev** [comment]
c# compiles down to IL. The actual language shipped in a DLL is IL, and our nuget packages only contain DLL's. 

Upgrading c# versions is a compile time concern, and not a runtime one. So upgrading to c#6 will not affect our users.

**Comment by TerribleDev** [comment]
thanks to @KBuroz
