### ISSUE TITLE
Ebay integration

### ISSUE THREAD

**Issue by faikmalik** [TerribleDev/OwinOAuthProviders#219]
Hi there. Im looking to implement ebay provider. Just wondering if you guys have already tried. any headstart? any help is appreciated

**Comment by TerribleDev** [comment]
Hello,

no one has made an ebay client AFAIK. Most of the time people copy the code from the github client, and adapt it to an ebay equivalent. Unfortunately, the way owin does oauth and how we integrate with the security models. Means we don't share a lot of code.
