### ISSUE TITLE
Steam Auth loginInfo returns null

### ISSUE THREAD

**Issue by Mithgroth** [TerribleDev/OwinOAuthProviders#225]
v 2.1.9

It used to work 4-5 days ago (I suppose), not loginInfo returns null.

![screenshot_3](https://user-images.githubusercontent.com/4046159/36063124-c4afa726-0e89-11e8-8324-21570117ac6d.jpg)

I suppose the problem is http://api.steampowered.com/ISteamUser/GetPlayerSummaries/v0002 returning 403:

![screenshot_6](https://user-images.githubusercontent.com/4046159/36063140-ee6e64ee-0e89-11e8-8173-caa47c273944.jpg)

**Comment by Mithgroth** [comment]
Sorry, the problem was with the API Key, not auth module.
Closing this.

**Comment by TerribleDev** [comment]
👍
