### ISSUE TITLE
VK API issues

### ISSUE THREAD

**Issue by TerribleDev** [TerribleDev/OwinOAuthProviders#230]
Hello,

We currently have 3 PRs for the same issue. 

#227 @alexus1024  
#228 @imaleksandr  
#229 @diseks 

Can we use this issue to discuss the problem, and decide which PR we should go with moving forward. Or propose a new PR with the union of all 3 approaches.

**Comment by TerribleDev** [comment]
I propose we go with #228 

@alexus1024 @imaleksandr @diseks

Does this seem reasonable?

**Comment by alexus1024** [comment]
I vote for 228
I don`t think this version setting in options from #229 is necessary: older version is not supported by VK anymore - it is the source of entire issue.
And my quick fix #227 is just too quick )

**Comment by imaleksandr** [comment]
Thanks guys. Cool that my code suits you.

**Comment by TerribleDev** [comment]
Great, I'll merge and deploy this tonight (barring any personal issues)
