### ISSUE TITLE
DiscordAuthenticationHandler: ClaimTypes.NameIdentifier uses context.UserName instead of context.Id

### ISSUE THREAD

**Issue by woutervs** [TerribleDev/OwinOAuthProviders#231]
As the title says.
Line 108 should be context.Id

**Comment by TerribleDev** [comment]
Why should it be? I'm willing to pull in this change if you justify the action.

**Comment by woutervs** [comment]
Because currently it holds context.Name in nameidentifier and context.Name in name.
There's no good reason to have two different claims with the same value and next to that the id for discord is more valuable information than the username since with just the username you can't make api requests to the discord api.

**Comment by TerribleDev** [comment]
hey, sorry I never replied back. That sounds good to me. Would you like to submit a PR?

@woutervs

**Comment by woutervs** [comment]
It was already merged on apr 1st ;)

Closing this.

**Comment by TerribleDev** [comment]
👍
