### ISSUE TITLE
Steam broken

### ISSUE THREAD

**Issue by master117** [TerribleDev/OwinOAuthProviders#234]
Recent changes in Steam seem to have broken the ExternalIdentity.

The same code that provided me with ExternalIdentity.Name ~6 days ago now returns null.

https://i.imgur.com/sGp7CF5.png

Other providers seem to have the same problem.

https://github.com/aspnet-contrib/AspNet.Security.OpenId.Providers/pull/42

**Comment by Mithgroth** [comment]
As a workaround, you can get Steam username by Steam profiles:

Take the Steam Id from ProviderKey:

`var steamId = (!string.IsNullOrEmpty(loginInfo.Login.ProviderKey)) ? loginInfo.Login.ProviderKey.Split('/')[5] : string.Empty;`

use that Id to call:

`"http://steamcommunity.com/profiles/" + steamId + "?xml=1"`

in this XML, `SteamID` is the user's Steam Name.

**Comment by TerribleDev** [comment]
Fixed with 2.23.0
