### ISSUE TITLE
[solved] LinkedIn .NET 4.5.1 fix (TLS1.1 EOL)

### ISSUE THREAD

**Issue by bennovakovic** [TerribleDev/OwinOAuthProviders#242]
Our linked in integration suddenly ground to a halt a few days ago and we had no idea until a user reported it to us.

After a few hours investigating the issue; it looks like LinkedIn upgraded their minimum TLS version to 1.2, but by default .NET 4.5.1 uses 1.1 (ref: https://www.linkedin.com/pulse/phase-two-our-tls-10-11-deprecation-plan-miles-mulcare/ )

The solution for us was to fork `OwinOAuthProviders` and make the following change:

https://github.com/bennovakovic/OwinOAuthProviders/commit/d78c1ab00cda1790d021946ccf40088d05b4e7dd

I hope this helps someone else who's having this issue.

**Comment by TerribleDev** [comment]
@bennovakovic you can do that in any app without forking the code. You can simply call that when your app first starts.
