### ISSUE TITLE
Salesforce oauth not working - TLS support

### ISSUE THREAD

**Issue by andy-fitch** [TerribleDev/OwinOAuthProviders#244]
I downloaded this project to test salesforce oauth signon into a mvc .net app. I think I got it all setup and configured just right. I was able to sign into salesforce, but after the redirect back into my .net mvc app - it looked like I was not authenticated.  In the _LoginPartial.cshtml shared view - the Request.IsAuthenticated was coming back false after I logged in.
This took a long time to figure out - but I read [this post](https://tutel.me/c/programming/questions/37356761/mvc+oauth+authentication+with+salesforce+returns+to+login+page) which described a very similar problem. 
In that article it talks about recent changes to Salesforces TLS support. It says to add this line to your code: System.Net.ServicePointManager.SecurityProtocol = System.Net.SecurityProtocolType.Tls11 | System.Net.SecurityProtocolType.Tls12;
I added it to the startup.auth.cs code and it fixed my issue.

I'd like to suggest updating this project to include this as the current project does not work out of the box.

Also - one other suggestion - It would be helpful to include some documentation on what the connected app configs need to be in salesforce. It took me a while to figure out that these scope permissions are needed: 
Access your basic information (id, profile, email, address, phone)
Access and manage your data (api)
Provide access to your data via the Web (web)
Perform requests on your behalf at any time (refresh_token, offline_access)
And that the callback url needs to be: https://localhost:portnum/signin-salesforce. That wasn't obvious to me.

**Comment by TerribleDev** [comment]
Thanks for the feedback. I've been away with family issues over the last several months so I apologize I never replied back sooner.

As a library we shouldn't set your SSL protocol types as we could override ones you want to have. 

I would love for you to add some documentation on the readme for the salesforce stuff. Unfortunately I've been out of the sales force game for a while, and I'm not sure I would be the best person to make those documents.
