### ISSUE TITLE
LinkedIn Oauth not working due to tls error

### ISSUE THREAD

**Issue by sjmohanta** [TerribleDev/OwinOAuthProviders#245]
LinkedIn login is failing due to TLS error. 

It worked after setting the protocol as below in method AuthenticateCoreAsync of LinkedInAuthenticationHandler class

```
ServicePointManager.SecurityProtocol = SecurityProtocolType.Tls |
                                       SecurityProtocolType.Tls11 |
                                       SecurityProtocolType.Tls12;
```

I have posted the issue here https://stackoverflow.com/questions/51673779/asp-net-mvc-linkedin-oauth-2-0-login-is-failling?noredirect=1#comment90319393_51673779

Can you please update the nuget package if above is solution to this issue.

Thanks

**Comment by nvanesch-logicmelon** [comment]
Confirmed resolved with the above

Our workaround is to set this in the Startup.cs

```
// https://github.com/TerribleDev/OwinOAuthProviders/issues/245
            // access_denied solution
            ServicePointManager.SecurityProtocol = SecurityProtocolType.Tls |
                            SecurityProtocolType.Tls11 |
                            SecurityProtocolType.Tls12;
```

before app.UseLinkedInAuthentication(linkedInAuthenticationOptions);

**Comment by TerribleDev** [comment]
Thanks you can also retarget to 4.6.2+ iirc
