### ISSUE TITLE
Spotify - Access and Refresh Tokens

### ISSUE THREAD

**Issue by scgough** [TerribleDev/OwinOAuthProviders#250]
Hi,
Great library. Is it possible to retrieve the Spotify Access and Refresh Tokens at the point of the user logging in? I'd like to be able to store them for later use in Spotify API requests.

Identity `LoginInfo` doesn't seem to contain any of that information so I'd like to be able to retrieve it.

**Comment by scgough** [comment]
I've created a PR for this. https://github.com/TerribleDev/OwinOAuthProviders/pull/251

**Comment by TerribleDev** [comment]
You should be able to use [this trick](https://github.com/TerribleDev/OwinOAuthProviders/issues/235#issuecomment-385823383) to get access to those tokens. We don't need to change the code at all AFAIK.

**Comment by scgough** [comment]
OK - thanks for the info. I'll give that a try before the PR https://github.com/TerribleDev/OwinOAuthProviders/pull/251 continues

**Comment by scgough** [comment]
OK - this does work. The only extra info missing (which isn't 100% essential) is the `scope` and `tokenType` returned from spotify. 

`tokenType` will always be `Bearer` and `scope` _should_ be whatever is sent in at the beginning.

**Comment by TerribleDev** [comment]
c# has closures, so you should be able to read the scope from the Options object

```csharp
            var opt = new TwitchAuthenticationOptions()
            {
                ClientId = "",
                ClientSecret = "",
                Provider = new TwitchAuthenticationProvider()
                {

                    OnAuthenticated = async z =>
                    {
                        opt.Scope // get the scope
                        z.Identity.AddClaim(new Claim("Picture", z.User.GetValue("logo").ToString()));
                    }
                    
                }
            };

```

**Comment by TerribleDev** [comment]
Oh I think I see what your asking for. You are looking to get back the scopes from Spotify

**Comment by TerribleDev** [comment]
~~If we get the scopes back in the response you could [add it to the authentication context](https://github.com/TerribleDev/OwinOAuthProviders/blob/master/src/Owin.Security.Providers.Spotify/Provider/SpotifyAuthenticatedContext.cs)~~

see my comment below

**Comment by TerribleDev** [comment]
Side note the User JObject should be everything we're given so it should also just be in there. I think this would get you the scopes if the json we get back has a scopes in a property called scopes

```csharp
            var opt = new TwitchAuthenticationOptions()
            {
                ClientId = "",
                ClientSecret = "",
                Provider = new TwitchAuthenticationProvider()
                {

                    OnAuthenticated = async z =>
                    {
                        JToken result;
                        z.User.TryGetValue("scopes", out result); // get the scope
                        var scopes = result.ToObject<List<string>>();
                        z.Identity.AddClaim(new Claim("Picture", z.User.GetValue("logo").ToString()));
                    }
                    
                }
            };

```

**Comment by scgough** [comment]
@TerribleDev Great, that's perfect thanks. I will find out the exact property name and try that out.
