### ISSUE TITLE
Customizable profile fields

### ISSUE THREAD

**Issue by doctorbrain** [TerribleDev/OwinOAuthProviders#43]
Hi.

Could you please somehow change the hardcoded
private const string UserInfoEndpoint = "https://api.linkedin.com/v1/people/~:(id,first-name,last-     name,formatted-name,email-address,public-profile-url)";

string to customizable alternative. I just want to be able to request additional user profile fields.

Thanks

**Comment by jerriep** [comment]
@doctorbrain I am a bit careful to just make it completely customisable as it opens it up for someone to request anything they want resulting in me not getting back at least some of the information I expect and breaking things badly.

Here are 2 other alternatives:
1. Tell me which extra fields you want and I will add them
2. Make a second call on OnAuthenticated, like this:

```
app.UseLinkedInAuthentication(new LinkedInAuthenticationOptions()
{
    ClientId = "",
    ClientSecret = "",
    Provider = new LinkedInAuthenticationProvider()
    {
        OnAuthenticated = async context =>
        {
            // Get the token
            var token = context.AccessToken;

            // Make a second call to LinkedIn API using HttpClient
            // ...   
        }
    }
});
```

**Comment by stefann42** [comment]
A second request seems unnecessary. Could you expose a List<string> ProfileFields (similar to Scope) on LinkedInAuthenticationOptions which you then concatenate (after validation) into the URL together with the fields needed by the core logic?

**Comment by jerriep** [comment]
Yes, it is unnecessary but the formatting for the fields need to be very specific because LinkedIn is fussy about the formatting of the request - which is why I was opposed to the original request of making it a free form field.

The simplest and easiest would be if you could just tell me which extra fields you need, like I suggested, and I add them to the request.

**Comment by paullooijmans** [comment]
I need access to some additional r_basicprofile fields for an app I'm building. I like @stefann42 proposal above to add a ProfileFields property on LinkedInAuthenticationOptions. If I prepare a pull request with that functionality would you consider accepting it?

**Comment by jerriep** [comment]
Yes please :)
