### ISSUE TITLE
Twitch support

### ISSUE THREAD

**Issue by TerribleDev** [TerribleDev/OwinOAuthProviders#46]
Would be awesome if this had twitch support. I could work on this, but I would need **a lot** of help/guidance. If someone else thinks they can do it faster, please do!

**Comment by TerribleDev** [comment]
Actually I was able to pull it off! Pull request submitted

**Comment by celluj34** [comment]
The twitch middleware is not working anymore. When I request credentials via

`var loginInfo = await AuthenticationManager.GetExternalLoginInfoAsync();`

null is always returned. I believe this has to do with the move from their v2 API to v3, and you may not be specifying that in the URIs. Since you don't, it assumes v3, and there may be a mismatch between some parameters, or URIs, or something else.

**Comment by jerriep** [comment]
@celluj34 It seems you know what the issue is. Can you please fix and submit a pull request?

**Comment by celluj34** [comment]
@jerriep it appears I was incorrect, it is functioning as expected. I was not using the correct path from my site. It should be "/signin-Twitch".

**Comment by jerriep** [comment]
Great, thanks :) I am closing this..

**Comment by TerribleDev** [comment]
Glad to hear people are using this :+1:

**Comment by markadrake** [comment]
Did you guys have any problem with the External Callback Page - I noticed @celluj34's comment, thank you - I was able to resolve that bit. But now it is redirected to the login form again, instead of being reaching /ExternalLoginCallback to setup the email address and account.

**Comment by markadrake** [comment]
Further examination is during ExternalLoginCallback, loginInfo is null and redirects to login form again. I've tested with multiple accounts.

**Comment by celluj34** [comment]
I should have been clearer in my earlier comment. In the twitch dev settings for your program, the return url should be <your App>/signin-twitch. It must match exactly. Then in your application, set the return url for the challenge result to your external login callback. Let me know if it still didn't work after that.

**Comment by markadrake** [comment]
Thanks for the quick reply @celluj34. The help is much appreciated.

After reading your comment I realized you meant I needed to also set the callback path in my own application - that was my hiccup. The other services seem to recognize this / send it by default. 

```
            app.UseTwitchAuthentication(new TwitchAuthenticationOptions()
            {
                CallbackPath = new PathString("/signin-twitch"),
                ClientId = AppConstants.TwitchClientId,
                ClientSecret = AppConstants.TwitchClientSecret
            });
```

My issue has been resolved! Thanks mate!
