### ISSUE TITLE
Question: Roadmap

### ISSUE THREAD

**Issue by jeroenslor** [TerribleDev/OwinOAuthProviders#52]
Hi,

What is the roadmap for this repo and does it make sence at this time to create pull request for new providers?

**Comment by jerriep** [comment]
@jeroenslor The roadmap is in limbo at the moment as far as ASP.NET 5 is concerned. A lot of these providers will not be required anymore for ASP.NET 5. At the moment however I cannot say which ones will still be needed, and which ones won't.

That being said, I am sure many people will still use ASP.NET 4.5 for some time to come, so pull requests are certainly welcome.

**Comment by jeroenslor** [comment]
@jerriep ok thanks for the quick response. What is the appropriate (aspnet 5) repo for providers that has a very specific implementation of the standard oauthhandler(from aspnet/security), for example evernote?

**Comment by jerriep** [comment]
@jeroenslor  There are very few "specific" implementations in ASP.NET 5. They have the same "specific" implementations as in ASP.NET 4.5 (i.e. MVC 5). What they do have however is a generic OAuth implementation which can be made to work with most OAuth services, by just specifying the correct Endpoints.

Have a look at the following sample:
https://github.com/aspnet/Security/blob/dev/samples/SocialSample/Startup.cs

See for example the Github configuration at line 116.

The point is that with this generic implementation the need to a library like mine, with very specific implementations, is not really needed anymore. As long as you know the correct endpoints you should be able to authorize against any provider, such as Evernote for example, using just the new generic OAuth provider.

Hope it makes sense, and you understand why I think this library may not be needed anymore in the future in most instances...

**Comment by jeroenslor** [comment]
@jerriep I have seen these samples and the spotify provider fits in nicely in that notification pattern but evernote uses the old oauth flow and is very similar to the twiiter implementation of the oauth handler which could not be done by just using the notifications / options

**Comment by jerriep** [comment]
In such a case I would say it makes sense to develop the provider and submit a pull request. When ASP.NET 5 comes out, we can convert it over to inherit from the proper ASP.NET 5 base classes...

**Comment by jeroenslor** [comment]
@jerriep a pull request to this repo you mean?

**Comment by jerriep** [comment]
Yes, if you would like to include it with this Nuget package.
