### ISSUE TITLE
GitHub: Scope initial value should be empty

### ISSUE THREAD

**Issue by AlexArchive** [TerribleDev/OwinOAuthProviders#59]
`GitHubAuthenticationOptions` [`Scope`](https://github.com/owin-middleware/OwinOAuthProviders/blob/master/Owin.Security.Providers/GitHub/GitHubAuthenticationOptions.cs#L134) has the following default value: 

``` c#
["user"]
```

I only need public profile information and therefore want to pass **no scope**. At the moment I have to do this: 

``` c#
var options = new GitHubAuthenticationOptions
{
    ClientId = "dc2119b9f611c6fec9c6",
    ClientSecret = "d028ee0e40ed333e53efa5dd2aba3e0e56bbfbee",
};
options.Scope.Clear();
app.UseGitHubAuthentication(options);
```

I propose that `Scope` default to an empty sequence (`[]`). This will enable the following syntax:

``` c#
app.UseGitHubAuthentication("dc2119b9f611c6fec9c6", "d028ee0e40ed333e53efa5dd2aba3e0e56bbfbee");
```

If you want to add the `user` scope again, you could do so easily using a collection initializer like so: 

``` c#
app.UseGitHubAuthentication(new GitHubAuthenticationOptions
{
    ClientId = "dc2119b9f611c6fec9c6",
    ClientSecret = "d028ee0e40ed333e53efa5dd2aba3e0e56bbfbee",
    Scope = { "user" }
});
```

I think you will agree that the syntax to opt-in is (1) more expressive and (2) easier to come about than the current syntax to opt-out.

Thoughts? I can submit a pull request if you want.

**Comment by Mavamaarten** [comment]
I agree that having no scope by default makes more sense.

**Comment by jerriep** [comment]
"user" scope is there so I can retrieve the user's public email address (if any). Changing this now may create a breaking change for other people who already use it and depend on it being here.

Is there any reason having the "user" scope included by default causes issues for you?

**Comment by AlexArchive** [comment]
Many thanks for your prompt response @jerriep. 

I am using social sign-in for authentication purposes only. I do not need authorization to perform an action on behalf of the user. 

According to the [documentation](https://developer.github.com/v3/oauth/#scopes)... 

> (user) grants read/write access to profile info only. Note that this scope includes user:email and user:follow.

I do not need the "user:email" or "user:follow" scopes. They prompt GitHub to tell users that my application needs permissions that it does not. In my experience users are reluctant to use social sign-in when permissions like these are required. 

I appreciate that the breaking change _may_ cause confusion for existing consumers (though there are some things you could do to reduce the impact like maintain a breaking change list) but for new consumers - like me - I think this change will reduce confusion.

Thank you for your consideration.

**Comment by jerriep** [comment]
@ByteBlast Yeah look, as far as the **inexplicable** permissions are concerned, all I can say is that hindsight is 20/20. I am not going to accept pull request for a breaking change that may confuse other users who have come to expect a certain behaviour.

There is a very easy workaround for you to ensure these permissions are not requested - simply clear the requested scopes.

**Comment by AlexArchive** [comment]
I think I could argue my point further but I shan't. You make a an argument that I can appreciate. 

I saw [this comment](https://github.com/owin-middleware/OwinOAuthProviders/issues/51#issuecomment-70596873) some time ago. Maybe you will consider this in the future.

**Comment by AlexArchive** [comment]
Thanks again @jerriep :smile:.

**Comment by jerriep** [comment]
@ByteBlast: I tell you what: I have been looking to offload this project to someone else as I do not have the time required to spend on it. 

If you are keen you can take it over along with all the decision making as well. Let me know and I can arrange to have repo and Nuget packages transferred to you.

**Comment by AlexArchive** [comment]
I am really flattered that you would entrust this awesome project to me :blush:. Thank you.

I will happily maintain this project for you.

**Comment by jerriep** [comment]
Cool. I sent you invite to the repo.

**NB:** Please send me your Nuget username so I can add you as owner there as well.

Dude, you're doing me, and the users of the library a favor as I cannot give it the attention it needs. This will become your baby and you will be responsible for decision making and taking it forward.

Good luck :)

**Comment by AlexArchive** [comment]
Thank you for the invitation. I have accepted it. 

My username on NuGet is [ByteBlast](https://www.nuget.org/profiles/ByteBlast).

**Comment by jerriep** [comment]
Added you as owner. Can you please send me an email at jerrie@jerriepelser.com so I have your email address and send you a quick note on my deployment procedure.

**Comment by AlexArchive** [comment]
I got the invitation and have accepted it - thank you. I also sent you a quick email from byteblast@gmail.com.
