### ISSUE TITLE
Request: PayPal provider

### ISSUE THREAD

**Issue by jerriep** [TerribleDev/OwinOAuthProviders#80]
<blockquote class="twitter-tweet" lang="en"><p>Hi <a href="https://twitter.com/jerriepelser">@jerriepelser</a> any plans for integrating PayPal login with <a href="http://t.co/mBMAkmZImF">http://t.co/mBMAkmZImF</a>?</p>&mdash; Taiseer Joudeh (@TJoudeh) <a href="https://twitter.com/TJoudeh/status/580748547441631233">March 25, 2015</a></blockquote>

<script async src="//platform.twitter.com/widgets.js" charset="utf-8"></script>

https://developer.paypal.com/webapps/developer/docs/integration/direct/paypal-oauth2/

**Comment by qanuj** [comment]
+1
