### ISSUE TITLE
BattleNet provider broken

### ISSUE THREAD

**Issue by patroza** [TerribleDev/OwinOAuthProviders#83]
The constructor accesses unitialized 'Options'.

https://github.com/owin-middleware/OwinOAuthProviders/blob/master/Owin.Security.Providers/BattleNet/BattleNetAuthenticationHandler.cs

**Comment by AlexArchive** [comment]
Thank you for raising this issue, @sickboy. I believe it was @KetaSwe who implemented this authentication provider. @KetaSwe, would you take a look at this?

@sickboy, if @KetaSwe is unavialable, I will tend to this myself.

**Comment by mariozski** [comment]
I created pull request with fix for this.
