### ISSUE TITLE
Anyone else having issue with LinkedIn provider ?

### ISSUE THREAD

**Issue by pksorensen** [TerribleDev/OwinOAuthProviders#87]
Today our users stopped being able to login with linked in.

Onlything I have right now from our traces at this point.

```
Response status code does not indicate success: 405 (Method Not Allowed).; TraceSource 'Owin.Security.Providers.LinkedIn.LinkedInAuthenticationMiddleware' event
[Thinktecture.IdentityServer.Core.Endpoints.AuthenticationController]: 4/7/2015 10:02:53 AM +00:00 -- External identity provider returned error: access_denied; TraceSource 'w3wp.exe' event
```

I inspect the webredirects and things seem to look fine and I suspect that its in the code to token exchange.

**Comment by pksorensen** [comment]
I am guessing this is the error: https://github.com/RockstarLabs/OwinOAuthProviders/blob/master/Owin.Security.Providers/LinkedIn/LinkedInAuthenticationHandler.cs#L238

Now, 405 could be from linked in, but i do not know at this point

**Comment by NoelOConnell** [comment]
I'm getting the same issue, only started today and I'm also getting the 405 (Method Not Allowed).

Still haven't figured out if it's LinkedIn or something to do with the code. 

I'm looking at the requests in Fiddler now and It seems fine so far.

**Comment by pksorensen** [comment]
ye. Was just discussing this with identity server guys. Suggestion was to debug it by hand doign the http calls to see where it goes wrong.  Must be in the code 2 token exchange.

My guess is that linkedin changed something since our codebase has not changed since last week and the issue started this morning

**Comment by pksorensen** [comment]
reproduced it now:  heres the response of the token.

https://gist.github.com/s093294/cbc7c8d3a3da0226d2e2

**Comment by pksorensen** [comment]
the request headers are also there in a comment now.

**Comment by AlexArchive** [comment]
Many thanks for bringing this to our attention, @s093294. I will look into this now. Do bare in mind that it was @jerriep who implemented this provider and not me - I have not touched this provider before. If you find a solution before me, please create a pull request. Cheers.

**Comment by pksorensen** [comment]
I dont think the provider is bad. I think its on linkedin https://www.linkedin.com/uas/oauth2/accessToken endpoint that is broken.

**Comment by pksorensen** [comment]
POST https://www.linkedin.com/uas/oauth2/accessToken HTTP/1.1
Content-Type: application/x-www-form-urlencoded
Host: www.linkedin.com
Cookie: bscookie="v=1&201504071234373bc02b47-9d08-477f-8375-b80b281ef416AQEptFjv8jXPI93YmF-H-3kvnwSLwBF8"; bcookie="v=2&46f6f299-6702-48bf-8634-7ba023bd5099"; lidc="b=LB23:g=218:u=215:i=1428410899:t=1428487523:s=AQH0wYHWtbTVED0CrzWvmbkbG4qIEQ3e"
Content-Length: 267
Expect: 100-continue
Connection: Keep-Alive

grant_type=authorization_code&code=AQTNeGrEj1QeV2MOudoi8T1fx1fov-05oSp5dg-HidNxpHtKJ_CkbfcsNyKvuY3eIztVtHQJb883P8QzB5vVvdjYYpR0T9eAjComHVc55quXCs6_RR8&redirect_uri=http%3A%2F%2Flocalhost%3A1729%2Fsignin-linkedin&client_id=&client_secret=

Just removed the secret/clientid, but above results in method not found.

**Comment by AlexArchive** [comment]
When did you first notice the problem? I wonder if LinkedIn have made a statement yet.

**Comment by pksorensen** [comment]
started this morning. noticed the error first time 5 hours ago.

Everything looks correct according to docs: https://developer.linkedin.com/docs/oauth2

I have seen nothing from linkedin

**Comment by pksorensen** [comment]
Created this:
https://stackoverflow.com/questions/29492598/post-https-www-linkedin-com-uas-oauth2-accesstoken-http-1-1-results-in-method

Got reply on twitter: https://twitter.com/LinkedInHelp/status/585429131652894720

**Comment by NoelOConnell** [comment]
+1 confirm that the provider isn't the problem.
I did the oauth2 request manually and still receiving the same error:
"The remote server returned an error: (405) Method Not Allowed."

So either a problem on LinkedIn's end or they changed something and decided not to tell developers again...

**Comment by jerriep** [comment]
Thanks for the investigation guys. Given it seems to be on the LinkedIn side I would suggest giving it a few hours and see whether it works itself out.

**Comment by AlexArchive** [comment]
I want to test this out but I cannot cannot so much as **register** an account with LinkedIn at the moment. 

It _always_ tells me the verification failed. I had a friend test this in America and it happens for him too.

![](http://i.imgur.com/hsE5lcn.png)

This _could_ be related to our problem here. It looks like their authentication server is being erratic.

**Comment by pksorensen** [comment]
there was an update in an answer that might help.
http://stackoverflow.com/a/29493329/871985

When confirmed (if this is the case) How fast can we fix this and get new nugets out? (Asking to find out if i should start making a local copy of the provider to hot fix it local (when solution exists)) or just wait for new nugets.

**Comment by ByteBlast** [comment]
If you can propose a fix. I will merge and update the NuGet package almost immediately.

**Comment by AlexArchive** [comment]
I am not sure. What do you think, @jerriep?

I am inclined to push an updated package as soon as we have a confirmed fix.

**Comment by jerriep** [comment]
Sorry guys, it is getting late evening already here by me, but if you get a fix for that by all means please update package and push :)

**Comment by AlexArchive** [comment]
Cool. I am still unable to create a LinkedIn account :angry:. @s093294, if you submit a pull request, I will be very grateful. I promise I will tend to it promptly.

**Comment by pksorensen** [comment]
Sure. Right now I dont think the fix is in the provider.  According to the SO answer, if the header is the issue, it is not set by this library sadly :( so not something that can be fixed easily.

**Comment by jlcj1974** [comment]
In .NET, we were able to work around this by explicitly disabling the Expect: 100-Continue for the LinkedIn API URI.  Something like this:

``` c#
protected void Application_Start()
{
var servicePoint = System.Net.ServicePointManager.FindServicePoint(new Uri("https://www.linkedin.com/uas/oauth2/accessToken";));
servicePoint.Expect100Continue = false;
}
```

I'm not proud of this but it's working locally.  

OK, we're getting intermittent issues with this solution, as well.  Stay tuned.

**Comment by pksorensen** [comment]
Just tested it also and noticed that it actually worked once and then after deploying it didnt work after all. Might be missing something.

**Comment by AlexArchive** [comment]
What happens when you use @jlcj1974's [branch](https://github.com/RockstarLabs/OwinOAuthProviders/pull/88)? I just tested it on localhost and it works.

**Comment by pksorensen** [comment]
Looks to be working here also. 

Should we push out some new nugets based on this to help people using the provider? Would be nice

**Comment by AlexArchive** [comment]
Awesome :smile:. Can you confirm that it works after deploying too?

**Comment by pksorensen** [comment]
Either i need to distribute local dlls to do so or wait for updates nugets. Can we generate prerelease packages?  But I dont see any reason why it would not work in production also with the change made.

**Comment by AlexArchive** [comment]
I am being mindful of this comment:

> Just tested it also and noticed that it actually worked once and then **after deploying it didnt work after all**. Might be missing something.

I interpreted that as "the solution works locally but not remotely." I will create a prerelease package now.

**Comment by pksorensen** [comment]
I can understand that. I might just have been a little to fast in deploying and could have found out locally that it didnt work as expected.

I still think its a good idea to add this as a prerelease until linkedin comes with a statement. This allows us to update and get a fix that work until we know if linkedin reverts anything or do further changes to the endpoint.

**Comment by AlexArchive** [comment]
I agree. Working on it now.

**Comment by AlexArchive** [comment]
**I just published a pre-release with the proposed fix. You can find it [here](https://www.nuget.org/packages/Owin.Security.Providers/1.17.0-pre).** Please report back.

**Comment by pksorensen** [comment]
Deployed to our staging deployment and sofar no issues. Deploying to production now also

**Comment by pksorensen** [comment]
I posted the prerelease as a answer also to my SO question: http://stackoverflow.com/questions/29492598/post-https-www-linkedin-com-uas-oauth2-accesstoken-http-1-1-results-in-method/29499394#29499394

**Comment by AlexArchive** [comment]
Nice one. 

I hope @LinkedIn acknowledge this apparent breaking change soon.

**Comment by AlexArchive** [comment]
Has anyone heard anything from @LinkedIn? (@s093294 @NoelOC @jerriep @jlcj1974)

I am wondering whether I should keep the [`LinkedIn-Fix`](https://github.com/RockstarLabs/OwinOAuthProviders/tree/LinkedIn-Fix) in a seperate branch or merge into `master` and release with `1.17` (opposed to `1.17-pre`). It depends if this temporary or not.

**Comment by pksorensen** [comment]
Havent heard anything yet. 

I would consider the fix stable. But there is always the chance that linkedin changes something again and that could be considered a new fix. 

I would keep it as a prerelease for a few days or until @LinkedIn gives a statement, since this will alert users of the lib to pay attention. If you release 1.17 and linkedin fixes/change something that yet again require a new update of the nugets, this change will reflect badly on the lib instead of on linkedin.

Just my 2cent.

**Comment by AlexArchive** [comment]
I _totally_ agree. 

:bear:

**Comment by jerriep** [comment]
Hey guys, thanks for all these fixes. 

From past experience, I think waiting for any official response from LinkedIn is futile, as communicating with developers is not their strong point ;)

That being said, I am totally cool with keeping it in pre-release mode for now. I am busy working my way through some pull requests, so hanging on before releasing it gives me more time to do that.

**Comment by CrazyMORF** [comment]
Hiya everybody,

I have the same issue with LinkedIn, but unfortunately Expect100Continue fix doesn't work for me (at least now). So for now I'm Authorization parameters (like grant_type, code, client_secret etc.) in query part of URI (instead of body of POST request to https://www.linkedin.com/uas/oauth2/accessToken endpoint).

Sad, but it works. Please checkout mine commit if you have same problems as me https://github.com/CrazyMORF/OwinOAuthProviders/commit/70d0f22d6480817f7fe03eb964357b28a497f41c

**Comment by pksorensen** [comment]
The prerelease package we created do still work here. (Just tested it).

**Comment by nikesh-thinkbridge** [comment]
Hi All,

I am also continuing to get the same error even after upgrading to pre release package. i.e access_denied. What should I check for?

**Comment by jerriep** [comment]
@nikesh-thinkbridge Have you followed this guide exactly?http://www.oauthforaspnet.com/providers/linkedin/guides/aspnet-mvc5/

**Comment by jerriep** [comment]
Another tip I can propose is to look at the network traffic in Chrome Developer tools. Make sure though that you have "Preserve Log" enabled so the requests does not clear everytime there is a redirect. A lot of time the clue is hidden somewhere inside the network traffic - you just need to go hunting...

![image](https://cloud.githubusercontent.com/assets/1006420/7047172/1448deac-de35-11e4-8741-6dfef3b738ce.png)

**Comment by nikesh-thinkbridge** [comment]
yes it was all working till yesterday morning, suddenly stopped working last evening. Then I installed the pre release version as suggested, but I am still getting the same error.

**Comment by nikesh-thinkbridge** [comment]
Sure...but the token call would be made by the middleware and not visible in the log right?
just an fyi..i am using an angular app as front end.

**Comment by jerriep** [comment]
It depends on what is wrong and when the error happens. When LinkedIn redirects back to your redirect URL it will happen in the browser, and it can happen that it includes more info inside that redirect response. 

Typically if redirect URLs does not match, scopes are incorrect, or other cases you will be able to see more details.

So don't just dismiss it out of hand. It is just _one_ way to try and track down the problem. If you do not see anything in the network traffic then we can eliminate that and move on to try something else.

**Comment by jerriep** [comment]
Of course if it does happen on the middleware level then you can always try and use Fiddler to monitor network traffic as well. 

Seeing as it does work for some people we need to track this down on your end.

I will try it quickly on my side and see whether I get the same issue.

**Comment by jerriep** [comment]
Yeah guys, it works 100% on my side as well. You will need to monitor the network traffic on your side with something like Fiddler to see whether you can get a clue about what may be wrong.

Is there anything "strange" about your configurations? Maybe a non-standard callback URL, or non standard scope or anything like that?

**Comment by nikesh-thinkbridge** [comment]
Thanks jerrie...My bad....Had changed the url for testing it on local which is on a different key than the production one. Changed it and all works like charm!!!
Sorry for the goof up...but thanks a lot. You guys saved a lot of heartburn!!!!!!

**Comment by jerriep** [comment]
No problem :) Glad you're sorted

**Comment by nikesh-thinkbridge** [comment]
Thanks to you! But what can we expect from our friends at Linked in......more surprises???!!

**Comment by jerriep** [comment]
Most probably ;) These companies aren't always very good with communicating changes to developers... :(

**Comment by jerriep** [comment]
Hey everyone. I release 1.17 by mistake without LinkedIn fix, but realised my mistake and released 1.17.1 with LI fix included.

I tested and all works fine. I will close this issue. 

If anything else comes up feel free to reopen or create a new issue

**Comment by trotin** [comment]
Hi everyone,

We applied the patch yesterday and it worked fine.
But around 7 hours ago, we received back an "access denied" error when we try to have an authentification using Owin.

Is there anyone with same problem ?

**Comment by pksorensen** [comment]
I cannot confirm the problem. Our linkedin sign on has worked since the updated package was added.

**Comment by jlcj1974** [comment]
We deployed yesterday and the patch is still working for us.

On Apr 9, 2015, at 11:36 AM, trotin <notifications@github.com<mailto:notifications@github.com>> wrote:

Hi everyone,

We applied the patch yesterday and it worked fine.
But around 7 hours ago, we received back an "access denied" error when we try to have an authentification using Owin.

Is there anyone with same problem ?

**Comment by AlexArchive** [comment]
Hi @trotin,

Many thanks for bringing another potential issue to our attention. Once I saw your comment I tested the patched LinkedIn provider on `localhost` (version [`1.17.1`](https://www.nuget.org/packages/Owin.Security.Providers/1.17.1)) and it still works. Can you please provide more detail? Could be this a human error, [as was the case for another user](https://github.com/RockstarLabs/OwinOAuthProviders/issues/87#issuecomment-90947578)?

I will leave this issue closed for now, as it seems to be working for everyone else.
